### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by pdurbin** [jggautier/dataverse-scripts#25]
It would be helpful for me to find a requirements.txt file in this repo to know what I need to pip install in order to run the scripts.

So far I've noticed that "requests" and "dateutil" is required. I assume there are others.

You could get specific in terms of versions if you like. In https://github.com/IQSS/dataverse-sample-data I "pinned" the version of pyDataverse like this:

```
pyDataverse==0.2.1
```

Here are some examples from https://pip.pypa.io/en/stable/cli/pip_install/#requirement-specifiers

```
SomeProject
SomeProject == 1.3
SomeProject >=1.2,<2.0
SomeProject[foo, bar]
SomeProject~=1.4.2
```

**Comment by jggautier** [comment]
I'll do that eventually when I test and add instructions for using a virtual environment (probably pipenv) to run these scripts.

**Comment by jggautier** [comment]
Okay, the [Installations section](https://github.com/jggautier/dataverse_scripts#installation) in the Readme has steps for using pipenv to install packages from the requirements.txt file I added.

The requirements.txt file doesn't list dateutil. I'm not sure why, but maybe because it already comes with the version of Python used for these scripts? I'm thinking that if anyone uses pipenv to run these scripts, they'll be using that version of Python (3.9.7).

If you try any of these things, let me know if you run into any issues.
